### ISSUE TITLE
Investigate origins reload when backend services path changes. 

### ISSUE THREAD

**Issue by mikkokar** [HotelsDotCom/styx#102]
## Background

Styx doesn't reload backend service changes correctly when the change is limited to the path prefix attribute only.

This issue can be demonstrated by modifying the following e2e test case:

`...2e-suite/src/test/scala/com/hotels/styx/admin/FileBasedOriginsFileChangeMonitorSpec.scala`

Modify this test so that only the only change to the backend service is the path component. I would expect the test case to pass, but it fails.

## Acceptance Criteria

I understand this issue is brief on the details. However raised it regardless for now with whatever information is available before it gets forgotten.

* Investigate why path attribute change doesn't behave as expected.
* Feel free to trash this issue if it turns out to be desired behaviour.

**Comment by dvlato** [comment]
Right now we are indexing Backend services in BackendServiceRouter by 'path' instead of by id. That means that we cannot reload a backend correctly if the path changes.  This will probably be addressed as part of the refactoring to separate routing from the 'ProxyToClientPipeline'. See line 102 of BackendServicesRouter for the latest revision on 2018/05/18:
https://github.com/HotelsDotCom/styx/blob/4de1dca3b52cb14f0ca93fc62d25c84ba08ceb86/components/proxy/src/main/java/com/hotels/styx/proxy/BackendServicesRouter.java#L102

**Comment by mikkokar** [comment]
Routing object configuration will end up deprecating this work.

**Comment by mikkokar** [comment]
Won't fix as BacendServicesRouter is going to be deprecated.
