### ISSUE TITLE
socketTimeoutMillis property in the connection pool configuration is not honoured. 

### ISSUE THREAD

**Issue by dvlato** [HotelsDotCom/styx#105]
## The problem
The property `socketTimeoutMillis` in the connection settings is completely ignored in Styx code (it never tries to set a timeout at all). 

## Detailed description
`com.hotels.styx.api.client.Connection.Settings.socketTimeoutMillis` is not read in any part of  Styx source code (except for some test cases that verify the config itself),  and thus it's never honoured.
 
## Acceptance criteria
* `com.hotels.styx.api.client.Connection.Settings.socketTimeoutMillis`  should be honoured, setting the timeout as expected.
* Documentation should be updated to reflect this change.

**Comment by mikkokar** [comment]
I suppose the `socketTimeoutMillis` is an old relic that ought to be removed. If I remember correctly it was later on substituted with `responseTimeout` setting which is applied at backend service level.

Also for the the `socketTimeoutMillis` has nothing to do with `SO_TIMEOUT` Netty channel option. This sets a time cap on blocking operations for old IO channels. See as a reference: [https://docs.oracle.com/javase/1.5.0/docs/api/java/net/SocketOptions.html#SO_TIMEOUT]. But since Styx doesn't use any blocking operations we don't care about `SO_TIMEOUT`.

The conclusion therefore is to remove `socketTimeoutMillis` from documentation and from the code.

**Comment by mikkokar** [comment]
PR #150
