### ISSUE TITLE
Add 4xx server response codes to styx documentation

### ISSUE THREAD

**Issue by mikkokar** [HotelsDotCom/styx#130]
## The problem

The 400, 408, etc (if any others?) response code is not documented in https://github.com/HotelsDotCom/styx/blob/master/docs/user-guide/response-codes.md.

## Acceptance criteria

The user guide response codes page contains the following information:
* The circumstances under which styx responds with 400.
* The circumstances under which styx responds with 408.

The relevant user manual page: https://github.com/HotelsDotCom/styx/blob/master/docs/user-guide/response-codes.md.

**Comment by kvosper** [comment]
We should create a separate page for this documentation, since 5xx response codes indicate a server error, whereas 4xx response codes are client errors.

The significance of this distinction is that server errors indicate that there is a problem that someone running Styx should look into, whereas client errors are likely to be caused by the end-users' actions.

**Comment by mikkokar** [comment]
@kvosper Please remember to close the issue after merging.
