### ISSUE TITLE
URL parsing bug with http://example.com//foo/bar

### ISSUE THREAD

**Issue by taer** [HotelsDotCom/styx#391]
When a URL comes into Styx like this

https://test.homeaway.co.uk//www.homeaway.co.uk/p6873759, it gets messed up inside of Styx. The request path that pops out in the request.path()

path=/p6873759

because styx uses URI.create to parse the path from the HTTP first line path, and a //foo/bar as URI encodes foo as the host.

 

It's here in Styx's Url class
```
        public static Builder url(String value) {
            URI uri = URI.create(value);
            return new Builder()
                    .scheme(uri.getScheme())
                    .authority(uri.getAuthority())
                    .path(uri.getRawPath())
                    .rawQuery(uri.getRawQuery())
                    .fragment(uri.getFragment()); 
```
 value here is just the contents from the first http line.
 

But, it also seems the downstream app is given the original request still.  So origin will see path of `//www.homeaway.co.uk/p6873759`, while styx logged and treated as `/p6873759`

**Comment by mikkokar** [comment]
Browsers would have parsed the URL and constructed an HTTP request before it is sent to styx. This is how Styx sees is:

    GET //www.homeaway.co.uk/p6873759 HTTP/1.1
    Host: localhost:8080
    User-Agent: curl/7.63.0
    Accept: */*

Because `//www.homeaway.co.uk/p6873759 HTTP/1.1` starts with `//` the `URI.create` treats it as authority part, and the rest as a path. 

It is correct behaviour for Styx to proxy the request as `//www.homeaway.co.uk/p6873759`, but it would be incorrect to expose `/p6873759` bit alone as a path component. Also it would be unclear how it gets reassembled back to the correct form when proxied.

I will investigate.

**Comment by mikkokar** [comment]
Styx proxies the correct URL to origins because `HttpRequestOperation.toNettyRequest` uses `url().toString()` in sending the request. This presumably puts together both authority and path components, thus re-assembling the original URL.

Okay. We now need to figure out how to extract the correct path component for use in Styx URL.

**Comment by mikkokar** [comment]
Hi @taer. I have a fix in here: https://github.com/mikkokar/styx/tree/issue-391-url-parsing. Could you give it a try please?
